### ISSUE TITLE
Switching bulb on issue

### ISSUE THREAD

**Issue by PhoenixMarie** [briandorey/tp-link-LB130-Smart-Wi-Fi-Bulb#8]
Hello, thanks for your job. The problem is when i`m trying to switch bulb on,(with the first code run)with this code:

import time
from tplight import LB130
def main():
    light = LB130("192.168.1.176")
    light.on()
if __name__ == "__main__":
    main()

 i`m getting an error:
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    main()
  File "demo.py", line 12, in main
    light = LB130("192.168.1.176")
  File "/home/bob/PROGRAMMING/tp-link-LB130-Smart-Wi-Fi-Bulb/tplight.py", line 73, in __init__
    self.__hue = int(data[col1][col2][col3]['hue'])
KeyError: 'hue'

but switching on and off works fine with this code(bulb initially is in turned on state):
import time
from tplight import LB130

def main():
    light = LB130("192.168.1.176")
    light.off()
    time.sleep(3)
    light.on()
    time.sleep(3)
    light.off()
    time.sleep(3)
    light.on()

if __name__ == "__main__":
    main()

**Comment by papabuck** [comment]
I saw this as well and used another utility to inspect the returned JSON for the susinfo when the bulb is on vs when the bulb is off.
They are a different structure!

I was able to check the status of the bulb 'on' state and use different decodings. Specifically I changed the code in the init routine (not the full routine but you will see the difference). Works for me.

                col1 = 'system'
                col2 = 'get_sysinfo'
                col3 = 'light_state'
                col4 = 'dft_on_state'
                self.device_id = str(data[col1][col2]['deviceId'])
                self.__alias = data[col1][col2]['alias']
                self.__on_off = int(data[col1][col2][col3]['on_off'])
                
                if( self.__on_off == 0) :
                    self.__hue = int(data[col1][col2][col3][col4]['hue'])
                    self.__saturation = int(data[col1][col2][col3][col4]['saturation'])
                    self.__brightness = int(data[col1][col2][col3][col4]['brightness'])
                    self.__color_temp = int(data[col1][col2][col3][col4]['color_temp'])
                else:
                    self.__hue = int(data[col1][col2][col3]['hue'])
                    self.__saturation = int(data[col1][col2][col3]['saturation'])
                    self.__brightness = int(data[col1][col2][col3]['brightness'])
                    self.__color_temp = int(data[col1][col2][col3]['color_temp'])

**Comment by CD215** [comment]
Hello, I have exactly the same problem. The reason I needed this library was to turn on the lamp from a python script in raspberry pi when motion was detected. 
It seems that you have to establish the connection (with the assignment light = LB130("x.x.x.x") when the bulb is turned on and keep the connection on. This is a bit of  a blocking point for now, but I will try to find a solution.
If I have not understood correctly please let me know.
